apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        - --console-address
        - :9001
        command:
        - minio
        image: quay.io/minio/minio:latest
        imagePullPolicy: Always
        name: container
        envs:
          - name: MINIO_ROOT_USER
            value: minioadmin
          - name: MINIO_ROOT_PASSWORD
            value: minioadmin
        ports:
        - containerPort: 9001
          name: console
          protocol: TCP
        - containerPort: 9000
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 2000Gi
        name: data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio
spec:
  port:
    targetPort: console
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-api
spec:
  port:
    targetPort: api
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
